### ISSUE TITLE
Add Holomems Emotes & Twitter username

### ISSUE THREAD

**Issue by AL3X-69** [AL3X-69/TakoBonker#18]
The [channels.json](https://github.com/AL3X-69/TakoBonker/blob/master/api/src/main/resources/channels.json) file of TakoAPI containing all the Hololive channels need to be updated with their respective emotes and twitter usename.

> Note:
> Emote are supported both as unicode and raw

https://github.com/AL3X-69/TakoBonker/blob/master/api/src/main/resources/channels.json

Example:
```json
{
  "name": "Ninomae Ina'nis",
  "id": "UCMwGHR0BTZuLsmjY_NT5Pwg",
  "emoji": "\uD83D\uDC19",
  "twitter": "ninomaeinanis",
  "color": -10332546
},
```

# Full list
## Emotes:
Hololive EN Gen 1 Myth
- [x] Ninomae Ina'nis
- [x] Gawr Gura
- [x] Takanashi Kiara
- [x] Calliope Mori
- [x] Amelia Watson

Project: HOPE
- [x] IRyS

Hololive EN Gen 2 Council
- [x] Nanashi Mumei
- [x] Ouro Kronii
- [x] Hakos Baelz
- [x] Tsukumo Sana
- [x] Ceres Fauna

Hololive JP Gen 0
- [x] Tokino Sora
- [x] Roboco
- [x] Sakura Miko
- [x] Hoshimachi Suisei

Inkk Music
- [x] AZKi

Hololive JP Gen 1
- [x] Yozora Mel
- [x] Shirakami Fubuki
- [x] Natsuiro Matsuri
- [x] Aki Rosenthal
- [x] Akai Haato

Hololive JP Gen 2
- [x] Minato Aqua
- [ ] Murasaki Shion
- [ ] Nakiri Ayame
- [ ] Yuzuki Choco
- [ ] Oozora Subaru

Hololive Gamers
- [ ] Ookami Mio
- [x] Nekomata Okayu
- [ ] Inugami Korone

Hololive JP Gen 3
- [ ] Usada Pekora
- [x] ~Uruha Rushia~ (*Removed due to Cover contract termination, see #19*)
- [ ] Shiranui Flare
- [ ] Shirogane Noel
- [ ] Houshou Marine

Hololive JP Gen 4
- [ ] Amane Kanata
- [ ] Tsunokami Watame
- [ ] Tokoyami Towa
- [ ] Himemori Luna

Hololive JP Gen 5
- [ ] Yukihana Lami
- [ ] Momosuzu Nene
- [ ] Shishiro Botan
- [ ] Omaru Polka

Hololive JP Gen 6 "HoloX"
- [ ] La+ Darkness
- [ ] Takane Lui
- [ ] Hakui Koyori
- [ ] Sakamata Chloe
- [ ] Kazama Iroha

Holostars Gen 1
- [ ] Hanasaki Miyabi
- [ ] Kanade Izuru
- [ ] Arurandeisu
- [ ] Rikkaroid

Holostars Gen 2
- [ ] Astel Leda
- [ ] Kishido Tema
- [ ] Yukoku Roberu

Holostars Gen 3
- [ ] Kageyama Shien
- [ ] Aragami Oga

Hololive ID Gen 1
- [ ] Ayunda Risu
- [ ] Moona Hoshinova
- [ ] Airani Lofifteen

Hololive ID Gen 2
- [ ] Kureiji Ollie
- [ ] Anya Melfissa
- [ ] Paviolia Reine

## Twitter usernames:
Hololive EN Gen 1 Myth
- [ ] Ninomae Ina'nis
- [ ] Gawr Gura
- [ ] Takanashi Kiara
- [ ] Calliope Mori
- [ ] Amelia Watson

Project: HOPE
- [ ] IRyS

Hololive EN Gen 2 Council
- [ ] Nanashi Mumei
- [ ] Ouro Kronii
- [ ] Hakos Baelz
- [ ] Tsukumo Sana
- [ ] Ceres Fauna

Hololive JP Gen 0
- [ ] Tokino Sora
- [ ] Roboco
- [ ] Sakura Miko
- [ ] Hoshimachi Suisei

Inkk Music
- [ ] AZKi

Hololive JP Gen 1
- [ ] Yozora Mel
- [ ] Shirakami Fubuki
- [ ] Natsuiro Matsuri
- [ ] Aki Rosenthal
- [ ] Akai Haato

Hololive JP Gen 2
- [ ] Minato Aqua
- [ ] Murasaki Shion
- [ ] Nakiri Ayame
- [ ] Yuzuki Choco
- [ ] Oozora Subaru

Hololive Gamers
- [ ] Ookami Mio
- [ ] Nekomata Okayu
- [ ] Inugami Korone

Hololive JP Gen 3
- [ ] Usada Pekora
- [x] ~Uruha Rushia~ (*Removed due to Cover contract termination, see #19*)
- [ ] Shiranui Flare
- [ ] Shirogane Noel
- [ ] Houshou Marine

Hololive JP Gen 4
- [ ] Amane Kanata
- [ ] Tsunokami Watame
- [ ] Tokoyami Towa
- [ ] Himemori Luna

Hololive JP Gen 5
- [ ] Yukihana Lami
- [ ] Momosuzu Nene
- [ ] Shishiro Botan
- [ ] Omaru Polka

Hololive JP Gen 6 "HoloX"
- [ ] La+ Darkness
- [ ] Takane Lui
- [ ] Hakui Koyori
- [ ] Sakamata Chloe
- [ ] Kazama Iroha

Holostars Gen 1
- [ ] Hanasaki Miyabi
- [ ] Kanade Izuru
- [ ] Arurandeisu
- [ ] Rikkaroid

Holostars Gen 2
- [ ] Astel Leda
- [ ] Kishido Tema
- [ ] Yukoku Roberu

Holostars Gen 3
- [ ] Kageyama Shien
- [ ] Aragami Oga

Hololive ID Gen 1
- [ ] Ayunda Risu
- [ ] Moona Hoshinova
- [ ] Airani Lofifteen

Hololive ID Gen 2
- [ ] Kureiji Ollie
- [ ] Anya Melfissa
- [ ] Paviolia Reine

**Comment by AL3X-69** [comment]
# Full list
## Emotes:
Hololive EN Gen 1 Myth
- [x] Ninomae Ina'nis
- [x] Gawr Gura
- [x] Takanashi Kiara
- [x] Calliope Mori
- [x] Amelia Watson

Project: HOPE
- [x] IRyS

Hololive EN Gen 2 Council
- [x] Nanashi Mumei
- [x] Ouro Kronii
- [x] Hakos Baelz
- [x] Tsukumo Sana
- [x] Ceres Fauna

Hololive JP Gen 0
- [x] Tokino Sora
- [x] Roboco
- [x] Sakura Miko
- [x] Hoshimachi Suisei

Inkk Music
- [x] AZKi

Hololive JP Gen 1
- [x] Yozora Mel
- [x] Shirakami Fubuki
- [x] Natsuiro Matsuri
- [x] Aki Rosenthal
- [x] Akai Haato

Hololive JP Gen 2
- [x] Minato Aqua
- [ ] Murasaki Shion
- [ ] Nakiri Ayame
- [ ] Yuzuki Choco
- [ ] Oozora Subaru

Hololive Gamers
- [ ] Ookami Mio
- [x] Nekomata Okayu
- [ ] Inugami Korone

Hololive JP Gen 3
- [ ] Usada Pekora
- [x] ~Uruha Rushia~ (*Removed due to Cover contract termination, see #19*)
- [ ] Shiranui Flare
- [ ] Shirogane Noel
- [ ] Houshou Marine

Hololive JP Gen 4
- [ ] Amane Kanata
- [ ] Tsunokami Watame
- [ ] Tokoyami Towa
- [ ] Himemori Luna

Hololive JP Gen 5
- [ ] Yukihana Lami
- [ ] Momosuzu Nene
- [ ] Shishiro Botan
- [ ] Omaru Polka

Hololive JP Gen 6 "HoloX"
- [ ] La+ Darkness
- [ ] Takane Lui
- [ ] Hakui Koyori
- [ ] Sakamata Chloe
- [ ] Kazama Iroha

Holostars Gen 1
- [ ] Hanasaki Miyabi
- [ ] Kanade Izuru
- [ ] Arurandeisu
- [ ] Rikkaroid

Holostars Gen 2
- [ ] Astel Leda
- [ ] Kishido Tema
- [ ] Yukoku Roberu

Holostars Gen 3
- [ ] Kageyama Shien
- [ ] Aragami Oga

Hololive ID Gen 1
- [ ] Ayunda Risu
- [ ] Moona Hoshinova
- [ ] Airani Lofifteen

Hololive ID Gen 2
- [ ] Kureiji Ollie
- [ ] Anya Melfissa
- [ ] Paviolia Reine

## Twitter usernames:
Hololive EN Gen 1 Myth
- [ ] Ninomae Ina'nis
- [ ] Gawr Gura
- [ ] Takanashi Kiara
- [ ] Calliope Mori
- [ ] Amelia Watson

Project: HOPE
- [ ] IRyS

Hololive EN Gen 2 Council
- [ ] Nanashi Mumei
- [ ] Ouro Kronii
- [ ] Hakos Baelz
- [ ] Tsukumo Sana
- [ ] Ceres Fauna

Hololive JP Gen 0
- [ ] Tokino Sora
- [ ] Roboco
- [ ] Sakura Miko
- [ ] Hoshimachi Suisei

Inkk Music
- [ ] AZKi

Hololive JP Gen 1
- [ ] Yozora Mel
- [ ] Shirakami Fubuki
- [ ] Natsuiro Matsuri
- [ ] Aki Rosenthal
- [ ] Akai Haato

Hololive JP Gen 2
- [ ] Minato Aqua
- [ ] Murasaki Shion
- [ ] Nakiri Ayame
- [ ] Yuzuki Choco
- [ ] Oozora Subaru

Hololive Gamers
- [ ] Ookami Mio
- [ ] Nekomata Okayu
- [ ] Inugami Korone

Hololive JP Gen 3
- [ ] Usada Pekora
- [x] ~Uruha Rushia~ (*Removed due to Cover contract termination, see #19*)
- [ ] Shiranui Flare
- [ ] Shirogane Noel
- [ ] Houshou Marine

Hololive JP Gen 4
- [ ] Amane Kanata
- [ ] Tsunokami Watame
- [ ] Tokoyami Towa
- [ ] Himemori Luna

Hololive JP Gen 5
- [ ] Yukihana Lami
- [ ] Momosuzu Nene
- [ ] Shishiro Botan
- [ ] Omaru Polka

Hololive JP Gen 6 "HoloX"
- [ ] La+ Darkness
- [ ] Takane Lui
- [ ] Hakui Koyori
- [ ] Sakamata Chloe
- [ ] Kazama Iroha

Holostars Gen 1
- [ ] Hanasaki Miyabi
- [ ] Kanade Izuru
- [ ] Arurandeisu
- [ ] Rikkaroid

Holostars Gen 2
- [ ] Astel Leda
- [ ] Kishido Tema
- [ ] Yukoku Roberu

Holostars Gen 3
- [ ] Kageyama Shien
- [ ] Aragami Oga

Hololive ID Gen 1
- [ ] Ayunda Risu
- [ ] Moona Hoshinova
- [ ] Airani Lofifteen

Hololive ID Gen 2
- [ ] Kureiji Ollie
- [ ] Anya Melfissa
- [ ] Paviolia Reine
